import type {  NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from './Navbar';
import axios from 'axios'

const baseUrl = 'https://api.staging.myautochek.com/v1/inventory/make?popular=true';

export async function getServerSideProps(){
  const res = await axios.get(baseUrl)
  const data =await res.data;

return{
  props:{
    data,
  }
}

}



const Home: NextPage = ({data}) => {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Autochek Africa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div className="container">
        {data.makeList.map((item,index)=>( 
          <p key={index}>{item.name}</p>
        ))}
      </div>
    </div>
    
  )
};


export default Home
